### ISSUE TITLE
Inconsistencies in translation (Discussion)

### ISSUE THREAD

**Issue by elomatreb** [cmllr/redundancy#111]
While modifying the translations for my recent PR, I noticed several inconsistencies.
- Is it a "directory" or a "folder"?
- Should we end system messages only with a dot or, if appropriate, an exclamation mark?
- Should we address the user directly or stay formal?

Additionally, I would like to ask anyone working with translations to never put HTML into translation strings, refrain from using string concatenation in conjunction with translation strings, and use `sprintf()` to output data in strings. If this is neglected, translations into languages with a different sentence structure than English or German could be severely limited.

While we're at it, I would like to suggest switching to a more "sophisticated" translation system. [GNU gettext](http://php.net/manual/en/book.gettext.php) allows for easy pluralization, contextual translation, and enables translators to use more comfortable translation tools like [Poedit](http://poedit.net/).

**Comment by cmllr** [comment]
Well, the translations grown up with the program. And with this process, there were many incostinstent solutions, e. g. the HTML parts. I must say that this inconsistency is my fault. 

I've added the label Redundancy 2.1.0 to this issue. When I reach the state of the program where I can start with this label, I will grep throught the code and will look witch languages values are used now to clean the translations a little bit. After that, whe can talk about removing HTML parts out of it, too. This process will be part of the general refactoring of the UI Subproject "Nys". But I don't think we will reach this milestone soon, because there are simply other issues with higher priorities which needed to be fixed first. 

(Additional, it will take some time until I can start the refactoring of "Nys", because currently there is only 1 active developer on the PHP parts, other subprojects, like the clients, are not active :/. Or to tell it more clear: We have a problem in the quantity of active collaborators and the tasks we have to do).

I've never worked with PHP and gettext before. I've only used it once on Gtk#. Is this part of the default PHP libraries? It is very important to prevent additional depencies for the project to allow running the cloud on a webspace only with PHP support. Another thing is the performance, but this will problably show up when it is implemented.

**Comment by elomatreb** [comment]
gettext is part of the standard libraries, and there should be no performance losses (Quite the opposite: Since nearly all gettext functions are direct C bindings, they should be _really_ fast).

If you don't mind, I would like to make a fork of redundancy and try to clear some of these issues, just to see if it would be possible without too much work.

**Comment by cmllr** [comment]
Thanks. But I've assigned myself to a few issues. On my dev environment, I have some of this issues already fixed (e. g. #105) so we dont duplicate the work. I will publish my local changes soon, so we can see what issues left then.

**Comment by cmllr** [comment]
In a first analysis, I've looked witch values are used in the UI. It seems to be about 143. In the old language file we have 403 values. I think we can remove a lot of old garbage, but maybe there will be a few more values which are not displayed on this analysis. 

An indicator might be the list below

https://gist.github.com/squarerootfury/3a6781b2f10045d96c3f

> Note: Not all values are on this list, I have to improve it first.

**Comment by elomatreb** [comment]
OK, I'll wait for your changes and update my fork as needed.

While we're at it, could we streamline the format of the translation keys? Some keys are delimited using Camel-Case while others use underscores. Replacing them should be a simple search-replace operation, nothing too complicated.
