### ISSUE TITLE
Cannot delete file when shared 

### ISSUE THREAD

**Issue by cmllr** [cmllr/redundancy#148]
When a share link is created, a file cannot be deleted (which is most likely an mySQL issue, deleting the entry in the FileSystem table also gives an error message complaining there's a relation to the SharedFileSystem table). 
Suggested bugfix: when deleting a file, check for shares and either silently remove them or ask for OK/abort.

(origin in issue #147) reported by @llebochequirit

**Comment by lebochequirit** [comment]
I can reproduce the bug under the following circumstances:
- user has no permissions to share, but to delete
- user tries to create a share, gets an error message (as in #147), but link is created
- file can't be deleted because of share link (user may not touch due to restriction)

Fix could be: extend delete permission to delete also the share link.

I can also affirm that the bug does _not_ show if a user with sufficient permissions shares a file and then deletes it. Guess that's because he has permissions on the share link.

So if you already fixed the link creation issue in #147, this one might get ...redundant. Har har.

Cheers,

L. B. Q. R.

**Comment by lebochequirit** [comment]
Update:

When sharing a file as a user with proper rights, the share link is created.
When deleting this file and uploading the same file (ie. a file with the same name) that file is still shared.

So deleting a file does obviously not touch the share link. No idea how that fits into my sharelink-permission-theory :-)

L.B.Q.R.

**Comment by cmllr** [comment]
That is strange,

when deleting a file, every share gets deleted previously. Could you please update your R2 Instance to the :new:  version? 

We can also chat on https://gitter.im/Redundancycloud/public, if you want ;)
